In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.base import BaseEstimator, TransformerMixin

sns.set_theme(style="whitegrid")
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("../Data/Train.csv")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (1000, 12)

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,C,Flight,2,5,306,6,high,M,45,3838,1
1,2,F,Ship,7,2,114,3,high,M,35,2710,1
2,3,B,Ship,7,2,215,7,medium,F,44,4152,0
3,4,A,Road,5,3,126,5,medium,M,54,2245,0
4,5,F,Ship,3,5,113,3,medium,M,43,1806,1

In [3]:
np.random.seed(42)
n = 1000
df = pd.DataFrame({
    'Product_importance': np.random.choice(['low','medium','high'], n),
    'Destination_City': np.random.choice(
        ['New York','London','Paris','Tokyo','Unknown'] + [f'City_{i}' for i in range(50)],
        n
    ),
    'Feature_x': np.random.normal(0,1,n),
    'Feature_y': np.random.normal(0,1,n)
})
print("Synthetic Data Created")
df.head()

Synthetic Data Created

  Product_importance Destination_City  Feature_x  Feature_y
0               high          City_49  -0.089736   0.555604
1                low            Paris   1.440117   0.089581
2               high          City_45  -0.676392  -0.197338
3               high          City_25   1.800940  -0.151273
4                low          City_34  -0.040158  -0.194908

In [4]:
print("Unique Product Importance:", df['Product_importance'].nunique())
print("Unique Destination City:", df['Destination_City'].nunique())

df[['Product_importance','Destination_City']].head()

Unique Product Importance: 3
Unique Destination City: 55

  Product_importance Destination_City
0               high          City_49
1                low            Paris
2               high          City_45
3               high          City_25
4                low          City_34